name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.4.0
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # code generation for contracts, shouldn't be imported outside of lib/src/builder/
  build: ^2.0.0
  build_config: ^1.0.0
  dart_style: ^2.0.0
  code_builder: ^4.0.0
  path: ^1.8.0

  pointycastle: ^3.6.0
  http: ^0.13.4
  uuid: ^3.0.6
  json_rpc_2: ^3.0.1
  stream_transform: ^2.0.0
  stream_channel: ^2.1.0
  eip55: ^1.0.2
  collection: ^1.16.0
  typed_data: ^1.3.0
  convert: ^3.0.1
  async: ^2.9.0

dev_dependencies:
  async: ^2.8.2
  build_runner: ^2.0.3
  build_test: ^2.1.0
  web_socket_channel: ^2.0.0
  coverage: ^1.1.0
  test: ^1.17.0
  lints: ^1.0.0
